import { KartClassDef, KartClassId } from '../../types/game';

export const KART_CLASSES: Record<KartClassId, KartClassDef> = {
  scout: {
    id: 'scout',
    name: 'Neon Scout',
    tagline: 'Hyper Speed & Agility',
    description: 'Ultra-lightweight composite chassis designed for razor-sharp turns and top-end straightaway speeds.',
    color: '#00f0ff',
    accentColor: '#38bdf8',
    glowColor: 'rgba(0, 240, 255, 0.6)',
    stats: {
      topSpeed: 380,
      acceleration: 480,
      handling: 4.8,
      weight: 0.8,
      maxHealth: 85,
      maxShield: 40,
      driftMultiplier: 1.2,
      cooldownReduction: 1.1,
    },
  },
  tank: {
    id: 'tank',
    name: 'Goliath Tank',
    tagline: 'Armored Juggernaut',
    description: 'Reinforced titanium plating with massive knockback resistance and double shield capacity. Heavy impact rammer.',
    color: '#ef4444',
    accentColor: '#f97316',
    glowColor: 'rgba(239, 68, 68, 0.6)',
    stats: {
      topSpeed: 310,
      acceleration: 340,
      handling: 3.4,
      weight: 1.7,
      maxHealth: 160,
      maxShield: 80,
      driftMultiplier: 0.85,
      cooldownReduction: 0.9,
    },
  },
  balanced: {
    id: 'balanced',
    name: 'Monad Striker',
    tagline: 'Battlefield All-Arounder',
    description: 'The standard issue Monad battle racer. Flawless balance of combat firepower, handling, and armor durability.',
    color: '#8354fe',
    accentColor: '#a855f7',
    glowColor: 'rgba(131, 84, 254, 0.6)',
    stats: {
      topSpeed: 345,
      acceleration: 410,
      handling: 4.2,
      weight: 1.0,
      maxHealth: 110,
      maxShield: 50,
      driftMultiplier: 1.0,
      cooldownReduction: 1.0,
    },
  },
  drift: {
    id: 'drift',
    name: 'Apex Drifter',
    tagline: 'Cornering King',
    description: 'Modified slip differential with instant Tier 3 Supreme drift charging and extended nitro duration.',
    color: '#eab308',
    accentColor: '#facc15',
    glowColor: 'rgba(234, 179, 8, 0.6)',
    stats: {
      topSpeed: 350,
      acceleration: 430,
      handling: 5.2,
      weight: 0.9,
      maxHealth: 95,
      maxShield: 45,
      driftMultiplier: 1.6,
      cooldownReduction: 1.05,
    },
  },
  cyber: {
    id: 'cyber',
    name: 'Quantum Phantom',
    tagline: 'High-Tech Specialist',
    description: 'Experimental Monad quantum drive with rapid weapon energy recharge and electromagnetic shockwave dampeners.',
    color: '#ec4899',
    accentColor: '#f43f5e',
    glowColor: 'rgba(236, 72, 153, 0.6)',
    stats: {
      topSpeed: 360,
      acceleration: 440,
      handling: 4.5,
      weight: 1.05,
      maxHealth: 100,
      maxShield: 65,
      driftMultiplier: 1.15,
      cooldownReduction: 1.35,
    },
  },
};
