import { WeaponDef, WeaponType } from '../../types/game';

export const WEAPONS: Record<WeaponType, WeaponDef> = {
  blaster: {
    id: 'blaster',
    name: 'Twin Blaster',
    icon: 'Zap',
    color: '#00f0ff',
    damage: 22,
    ammo: 5,
    cooldown: 280,
    projectileSpeed: 680,
    range: 650,
    description: 'Fires fast twin plasma bolts with rapid velocity.',
  },
  vulcan: {
    id: 'vulcan',
    name: 'Gatling Vulcan',
    icon: 'Flame',
    color: '#f97316',
    damage: 12,
    ammo: 14,
    cooldown: 90,
    projectileSpeed: 750,
    range: 580,
    description: 'Devastating high-rate-of-fire bullet stream that peppers opponents.',
  },
  laser: {
    id: 'laser',
    name: 'Railgun Laser',
    icon: 'Radio',
    color: '#a855f7',
    damage: 48,
    ammo: 2,
    cooldown: 800,
    projectileSpeed: 1400,
    range: 900,
    description: 'Instant penetrating beam that rips through shields and armor in a straight line.',
  },
  mine: {
    id: 'mine',
    name: 'Proximity Mine',
    icon: 'Bomb',
    color: '#ef4444',
    damage: 55,
    ammo: 3,
    cooldown: 500,
    range: 120, // Blast radius
    description: 'Drops an explosive armed mine behind you. Detonates upon enemy contact.',
  },
  shockwave: {
    id: 'shockwave',
    name: 'EMP Shockwave',
    icon: 'Activity',
    color: '#38bdf8',
    damage: 30,
    ammo: 2,
    cooldown: 650,
    range: 200,
    description: 'Unleashes a 360° sonic pulse that repels nearby karts and destroys incoming shots.',
  },
  emp: {
    id: 'emp',
    name: 'EMP Disruptor',
    icon: 'WifiOff',
    color: '#eab308',
    damage: 18,
    ammo: 2,
    cooldown: 700,
    projectileSpeed: 520,
    range: 600,
    duration: 2500,
    description: 'Fires an electric orb that temporarily paralyzes steering and disables boost.',
  },
  cryo: {
    id: 'cryo',
    name: 'Cryo Missile',
    icon: 'Snowflake',
    color: '#67e8f9',
    damage: 28,
    ammo: 2,
    cooldown: 750,
    projectileSpeed: 600,
    range: 700,
    duration: 2000,
    description: 'Launches a homing ice rocket that encases the victim in an uncontrollable ice block.',
  },
  rocket: {
    id: 'rocket',
    name: 'Rocket Boost Rush',
    icon: 'Rocket',
    color: '#ff007a',
    damage: 40,
    ammo: 2,
    cooldown: 900,
    duration: 1500,
    description: 'Ignites supercharged rocket thrusters, ramming karts and burning pursuers in your flame trail.',
  },
};
