// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface ISmashToken {
    function mintReward(address recipient, uint256 amount) external returns (bool);
}

/**
 * @title KartRewardVault
 * @notice Distributes match earnings and daily quest completion rewards on Monad Testnet
 */
contract KartRewardVault {
    address public owner;
    ISmashToken public immutable smashToken;

    // Track total claimed per player
    mapping(address => uint256) public totalRewardsClaimed;
    mapping(address => uint256) public lastMatchClaimTimestamp;
    mapping(bytes32 => bool) public processedMatchIds;

    uint256 public constant BASE_WIN_REWARD = 25 * 10**18; // 25 SMASH per win
    uint256 public constant KILL_BONUS = 5 * 10**18;       // 5 SMASH per kill
    uint256 public constant QUEST_REWARD = 50 * 10**18;    // 50 SMASH per quest

    event MatchRewardClaimed(
        address indexed player,
        bytes32 indexed matchId,
        uint256 kills,
        bool isWinner,
        uint256 totalAmount
    );

    event QuestRewardClaimed(
        address indexed player,
        string questId,
        uint256 rewardAmount
    );

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    constructor(address _smashToken) {
        owner = msg.sender;
        smashToken = ISmashToken(_smashToken);
    }

    /**
     * @notice Claims rewards for completed match
     * @param matchId Unique hash generated by match session
     * @param kills Number of opponents destroyed
     * @param isWinner Whether player placed 1st
     */
    function claimMatchReward(
        bytes32 matchId,
        uint256 kills,
        bool isWinner
    ) external returns (uint256) {
        require(!processedMatchIds[matchId], "Match already claimed");
        require(kills <= 50, "Unrealistic kill count");

        processedMatchIds[matchId] = true;
        lastMatchClaimTimestamp[msg.sender] = block.timestamp;

        uint256 amount = (kills * KILL_BONUS);
        if (isWinner) {
            amount += BASE_WIN_REWARD;
        } else {
            amount += (BASE_WIN_REWARD / 5); // Consolation reward
        }

        totalRewardsClaimed[msg.sender] += amount;
        require(smashToken.mintReward(msg.sender, amount), "Minting reward failed");

        emit MatchRewardClaimed(msg.sender, matchId, kills, isWinner, amount);
        return amount;
    }

    /**
     * @notice Claims rewards for daily quest completion
     */
    function claimQuestReward(string calldata questId) external returns (uint256) {
        totalRewardsClaimed[msg.sender] += QUEST_REWARD;
        require(smashToken.mintReward(msg.sender, QUEST_REWARD), "Minting reward failed");

        emit QuestRewardClaimed(msg.sender, questId, QUEST_REWARD);
        return QUEST_REWARD;
    }
}
